#!/bin/bash
# Created by the VLSCI job script generator
# Wed Oct 24 2012 16:29:01 GMT+1100 (EST)

# Queue for the job:
#PBS -q batch

# The name of the job:
#PBS -N tophatAlign

# Maximum number of CPU cores used by the job:
#PBS -l procs=8

# The amount of memory in gigabytes per process in the job:
#PBS -l pvmem=4gb

# Use this email address:
#PBS -M dvbrown@student.unimelb.edu.au

# The maximum running time of the job in days:hours:mins:secs
#PBS -l walltime=0:1:0:0

# Run the job from the directory where it was launched:
cd $PBS_O_WORKDIR

# The modules to load:
module load bowtie-gcc/2.0.0-b7
module load samtools-gcc/0.1.16
module load tophat/2.0.4

# The job command(s):
mpiexec ./121024TopHat2.sh